const defaultContent = {
  key: 'main',
  heroHello: "Hello, I'm",
  heroName: 'Japheth Mwinekpieng Lamuo',
  heroRole: 'Backend Developer',
  heroLede: 'I build REST APIs with Node.js, Express, and MongoDB. I am based in Accra, Ghana, and open to remote work.',
  aboutParagraphs: [
    "I am a backend developer in Accra, Ghana. I am taking the Backend Development Track at BeTechified Tech Academy while studying Electrical and Electronics Engineering at the University of Energy and Natural Resources.",
    "I started out writing CRUD APIs that kept everything in memory and testing them by hand in Postman. Since then I have shipped services with real validation, indexing, and authentication on them. What I like about backend work is that it is quiet when it is right. You only hear about it when something breaks.",
    "I am looking for junior backend roles and freelance work, remote friendly. If you work in Node.js and MongoDB, we will get on fine.",
  ],
  skills: {
    runtime: ['Node.js'],
    framework: ['Express.js'],
    database: ['MongoDB', 'Mongoose'],
    validation: ['Joi'],
    auth: ['JWT', 'bcrypt'],
    tooling: ['Git', 'Postman', 'dotenv'],
    deploy: ['Render', 'MongoDB Atlas'],
  },
};

const defaultProjects = [
  {
    method: 'GET',
    route: '/projects/portfolio',
    status: '200 OK',
    title: 'This Portfolio',
    description: 'The site you are reading. A server-rendered Express app with EJS templates, a MongoDB-backed content API, a JWT-protected admin panel for editing projects and copy, a rate-limited contact endpoint, and my own analytics instead of third-party trackers.',
    tags: ['Node.js', 'Express', 'EJS', 'MongoDB', 'JWT', 'Resend'],
    liveUrl: '',
    sourceUrl: 'https://github.com/Japheth-l',
    order: 0,
  },
  {
    method: 'GET',
    route: '/projects/notes-api',
    status: '200 OK',
    title: 'Notes API',
    description: 'A REST API for notes with Joi-validated input, page-and-limit pagination that runs the count query in parallel, and a weighted full-text index across title and content. Deployed on Render.',
    tags: ['Node.js', 'Express', 'MongoDB', 'Mongoose', 'Joi'],
    liveUrl: 'https://notes-api-k7fb.onrender.com',
    sourceUrl: 'https://github.com/Japheth-l/notes-api',
    order: 1,
  },
  {
    method: 'POST',
    route: '/projects/blog-api/auth',
    status: '201 Created',
    title: 'Blog API with JWT Auth',
    description: 'A blogging backend with token-based authentication. Signup, login, and protected routes behind JWT middleware, so only the right people can publish or edit a post.',
    tags: ['Node.js', 'Express', 'JWT', 'bcrypt', 'MongoDB'],
    sourceUrl: 'https://github.com/Japheth-l/blog-api-auth',
    order: 2,
  },
  {
    method: 'PUT',
    route: '/projects/ecommerce-api/products',
    status: '200 OK',
    title: 'E-commerce Product Management API',
    description: 'Team project at BeTechified. I owned the products module: full CRUD, Mongoose schema design, Joi validation, regex-based search, and pagination on the product listing endpoints.',
    tags: ['Node.js', 'Express', 'MongoDB', 'Joi', 'Team project'],
    order: 3,
  },
  {
    method: 'GET',
    route: '/projects/todo-api',
    status: '200 OK',
    title: 'Todo API',
    description: 'Started as an in-memory CRUD exercise, then moved to MongoDB Atlas so the data survived a restart. That gap is the thing it taught me.',
    tags: ['Node.js', 'Express', 'MongoDB Atlas'],
    sourceUrl: 'https://github.com/Japheth-l',
    order: 4,
  },
];

module.exports = { defaultContent, defaultProjects };
